import Link from "next/link";
import { RequirementActions, RequirementCreateForm } from "@/components/inventory/inventory-forms";
import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { requirePagePermission } from "@/modules/auth/application/page-access";
import { PERMISSIONS } from "@/modules/auth/domain/permissions";
import { listInventory,listMaterialRequirements } from "@/modules/inventory/application/queries";
const statuses:Record<string,string>={PLANNED:"Запланировано",PREPARED:"Подготовлено",PARTIALLY_ISSUED:"Частично выдано",ISSUED:"Выдано",PARTIALLY_RETURNED:"Частично возвращено",RETURNED:"Возвращено",USED:"Использовано",WRITTEN_OFF:"Списано"};
export default async function RequirementsPage(){await requirePagePermission(PERMISSIONS.INVENTORY_READ);const[data,catalog]=await Promise.all([listMaterialRequirements(),listInventory()]);return <div className="space-y-6"><PageHeader title="Материалы проектов" description="Потребность, транзакционный резерв, выдача монтажу и фактический расход"/><Button asChild variant="outline"><Link href="/inventory">Назад на склад</Link></Button>{data.canManage?<RequirementCreateForm projects={data.projects} items={catalog.items.filter(x=>x.isActive).map(x=>({id:x.id,name:x.name,unit:x.unit}))} estimates={data.estimates} installations={data.installations}/>:null}<div className="grid gap-4 lg:grid-cols-2">{data.requirements.map(req=><Card key={req.id} className={req.missing>0?"border-amber-400":""}><CardContent className="space-y-3 pt-5"><div className="flex justify-between gap-2"><div><b>{req.item.name}</b><div className="text-muted-foreground text-xs">Проект {req.project.number}{req.room?` · ${req.room.name}`:""}</div></div><Badge>{statuses[req.status]??req.status}</Badge></div><div className="grid grid-cols-3 gap-2 text-sm"><div>Требуется<br/><b>{Number(req.required)} {req.item.unit}</b></div><div>На складе<br/><b>{req.onHand}</b></div><div>Резерв проекта<br/><b>{Number(req.reserved)}</b></div><div>Выдано<br/><b>{Number(req.issued)}</b></div><div>Не хватает<br/><b className={req.missing>0?"text-destructive":""}>{req.missing}</b></div><div>Заказать<br/><b>{req.toOrder}</b></div></div>{data.canManage?<RequirementActions requirementId={req.id} locations={data.locations.map(x=>({id:x.id,name:x.name}))} maxReturn={Number(req.issued)} reservations={req.reservations.map(r=>({id:r.id,label:`${r.balance.location.name}: свободно ${Number(r.quantity)-Number(r.issued)-Number(r.released)}`}))}/>:null}</CardContent></Card>)}</div></div>}