export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",
  USER_READ: "user.read",
  USER_MANAGE: "user.manage",
  ROLE_READ: "role.read",
  ROLE_MANAGE: "role.manage",
  AUDIT_READ: "audit.read",
  PROFILE_READ: "profile.read",
  PROFILE_UPDATE: "profile.update",
  LEAD_CREATE: "lead.create",
  LEAD_OWN_READ: "lead.own.read",
  LEAD_READ: "lead.read",
  LEAD_MANAGE: "lead.manage",
  PROJECT_READ: "project.read",
  PROJECT_MANAGE: "project.manage",
  MEASUREMENT_ASSIGNED_READ: "measurement.assigned.read",
  MEASUREMENT_ASSIGNED_MANAGE: "measurement.assigned.manage",
  ESTIMATE_READ: "estimate.read",
  ESTIMATE_CREATE: "estimate.create",
  ESTIMATE_CLIENT_PRICE_READ: "estimate.client-price.read",
  ESTIMATE_CLIENT_PRICE_MANAGE: "estimate.client-price.manage",
  ESTIMATE_INTERNAL_PRICE_READ: "estimate.internal-price.read",
  TARIFF_MANAGE: "tariff.manage",
  INSTALLATION_SCHEDULE: "installation.schedule",
  INSTALLATION_ASSIGNED_READ: "installation.assigned.read",
  INSTALLATION_ASSIGNED_MANAGE: "installation.assigned.manage",
  FINANCE_READ: "finance.read",
  FINANCE_MANAGE: "finance.manage",
  ANALYTICS_READ: "analytics.read",
  ANALYTICS_SELF_READ: "analytics.self.read",
  NOTIFICATION_READ: "notification.read",
  INVENTORY_READ: "inventory.read",
  INVENTORY_MANAGE: "inventory.manage",
  CUSTOMER_PHONE_READ: "customer.phone.read",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const definition = (
  code: PermissionCode,
  name: string,
  description: string,
  category: string,
) => ({ code, name, description, category });

export const PERMISSION_DEFINITIONS: ReadonlyArray<{
  code: PermissionCode;
  name: string;
  description: string;
  category: string;
}> = [
  definition(
    PERMISSIONS.DASHBOARD_READ,
    "Просмотр главной панели",
    "Доступ к общей рабочей панели",
    "Рабочее пространство",
  ),
  definition(
    PERMISSIONS.USER_READ,
    "Просмотр пользователей",
    "Просмотр списка и карточек пользователей",
    "Администрирование",
  ),
  definition(
    PERMISSIONS.USER_MANAGE,
    "Управление пользователями",
    "Создание, изменение, блокировка и сброс пароля",
    "Администрирование",
  ),
  definition(
    PERMISSIONS.ROLE_READ,
    "Просмотр ролей",
    "Просмотр ролей и назначенных разрешений",
    "Администрирование",
  ),
  definition(
    PERMISSIONS.ROLE_MANAGE,
    "Управление ролями",
    "Изменение набора разрешений ролей",
    "Администрирование",
  ),
  definition(
    PERMISSIONS.AUDIT_READ,
    "Просмотр журнала действий",
    "Доступ к аудиту важных изменений",
    "Безопасность",
  ),
  definition(
    PERMISSIONS.PROFILE_READ,
    "Просмотр профиля",
    "Просмотр собственного профиля",
    "Профиль",
  ),
  definition(
    PERMISSIONS.PROFILE_UPDATE,
    "Изменение профиля",
    "Изменение имени и собственного пароля",
    "Профиль",
  ),
  definition(
    PERMISSIONS.LEAD_CREATE,
    "Создание лидов",
    "Быстрое создание новой заявки",
    "Лиды",
  ),
  definition(
    PERMISSIONS.LEAD_OWN_READ,
    "Свои лиды",
    "Просмотр только собственных заявок",
    "Лиды",
  ),
  definition(
    PERMISSIONS.LEAD_READ,
    "Просмотр лидов",
    "Просмотр операторской очереди и карточек лидов",
    "Лиды",
  ),
  definition(
    PERMISSIONS.LEAD_MANAGE,
    "Обработка лидов",
    "Звонки, задачи, замеры, отказы и квалификация",
    "Лиды",
  ),
  definition(
    PERMISSIONS.PROJECT_READ,
    "Просмотр проектов",
    "Просмотр списка и карточек клиентских проектов",
    "Проекты",
  ),
  definition(
    PERMISSIONS.PROJECT_MANAGE,
    "Управление проектами",
    "Статусы, ответственные, задачи и события проекта",
    "Проекты",
  ),
  definition(
    PERMISSIONS.CUSTOMER_PHONE_READ,
    "Полный телефон клиента",
    "Серверный доступ к полному номеру телефона клиента",
    "Персональные данные",
  ),
  definition(
    PERMISSIONS.MEASUREMENT_ASSIGNED_READ,
    "Назначенные замеры",
    "Просмотр только назначенных сотруднику замеров",
    "Замеры",
  ),
  definition(
    PERMISSIONS.MEASUREMENT_ASSIGNED_MANAGE,
    "Заполнение замеров",
    "Черновики и технические данные назначенных замеров",
    "Замеры",
  ),
  definition(
    PERMISSIONS.ESTIMATE_READ,
    "Просмотр смет",
    "Просмотр технического состава смет без ценовых прав",
    "Сметы",
  ),
  definition(
    PERMISSIONS.ESTIMATE_CREATE,
    "Создание смет",
    "Серверный расчёт и сохранение версий смет",
    "Сметы",
  ),
  definition(
    PERMISSIONS.ESTIMATE_CLIENT_PRICE_READ,
    "Клиентская цена",
    "Просмотр клиентских цен и итогов",
    "Финансы",
  ),
  definition(
    PERMISSIONS.ESTIMATE_CLIENT_PRICE_MANAGE,
    "Изменение клиентской цены",
    "Управление скидками и клиентскими ценами",
    "Финансы",
  ),
  definition(
    PERMISSIONS.ESTIMATE_INTERNAL_PRICE_READ,
    "Внутренняя себестоимость",
    "Просмотр себестоимости и внутренний PDF",
    "Финансы",
  ),
  definition(
    PERMISSIONS.TARIFF_MANAGE,
    "Управление тарифами",
    "Изменение стоимости материалов, работ, зон и коэффициентов",
    "Сметы",
  ),
  definition(
    PERMISSIONS.INSTALLATION_SCHEDULE,
    "Назначение монтажей",
    "Создание выездов и назначение монтажных бригад",
    "Монтажи",
  ),
  definition(
    PERMISSIONS.INSTALLATION_ASSIGNED_READ,
    "Назначенные монтажи",
    "Просмотр только монтажей назначенного сотрудника",
    "Монтажи",
  ),
  definition(
    PERMISSIONS.INSTALLATION_ASSIGNED_MANAGE,
    "Ход монтажа",
    "Статусы, фотографии и фактические материалы своего монтажа",
    "Монтажи",
  ),
  definition(
    PERMISSIONS.FINANCE_READ,
    "Просмотр финансов",
    "Просмотр финансовых показателей проектов",
    "Финансы",
  ),
  definition(
    PERMISSIONS.FINANCE_MANAGE,
    "Управление финансами",
    "Изменение договора, платежей и себестоимости",
    "Финансы",
  ),
  definition(
    PERMISSIONS.ANALYTICS_READ,
    "Управленческая аналитика",
    "Просмотр общих операционных и финансовых показателей",
    "Аналитика",
  ),
  definition(
    PERMISSIONS.ANALYTICS_SELF_READ,
    "Личная аналитика",
    "Просмотр только собственных безопасных показателей",
    "Аналитика",
  ),
  definition(
    PERMISSIONS.NOTIFICATION_READ,
    "Уведомления",
    "Просмотр и отметка собственных внутренних уведомлений",
    "Уведомления",
  ),
  definition(
    PERMISSIONS.INVENTORY_READ,
    "Просмотр склада",
    "Остатки, резервы, дефицит и движения материалов",
    "Склад",
  ),
  definition(
    PERMISSIONS.INVENTORY_MANAGE,
    "Управление складом",
    "Атомарное изменение складских остатков и резервов",
    "Склад",
  ),
];
